version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: my_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ahmed
      MYSQL_DATABASE: assignment_5
      MYSQL_USER: user
      MYSQL_PASSWORD: ahmed
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
